<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$product = $block->getProduct();
$productImageUrl = $block->getProductImageUrl();
$imageWidth = $block->getImageWidth();
$imageHeight = $block->getImageHeight();
$productImage = $block->getProductImage();
?>

<img fetchpriority="high" loading="eager" 
class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>lazy text-[0] mx-auto transition duration-1000 ease-in-out group-hover:scale-[1.04]" id="product-image-container-list-<?= $escaper->escapeHtmlAttr($product->getId()) ?>" 
data-src="<?= $escaper->escapeUrl($productImageUrl) ?>" 
width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>" 
height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>" 
alt="<?= $escaper->escapeHtmlAttr($productImage->getLabel()) ?>"  
onerror="this.style.display='none'" 
title="<?= $escaper->escapeHtmlAttr($productImage->getLabel()) ?>" />
<span class="product photo skeleton skeleton-box absolute text-gray-400 bg-gray-100 inset-0 w-full h-full z-10 flex justify-center items-center">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12">
        <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
</span>